apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: managed-namespace
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
